### ISSUE TITLE
Error while enabling jupyter_http_over_ws extension

### ISSUE THREAD

**Issue by Kshitij09** [googlecolab/jupyter_http_over_ws#11]
I'm following the instructions described [here](https://research.google.com/colaboratory/local-runtimes.html).

The very second step to enable `jupyter_http_over_ws` jupyter extension gives following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-serverextension", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python2.7/dist-packages/notebook/serverextensions.py", line 293, in start
    super(ServerExtensionApp, self).start()
  File "/usr/local/lib/python2.7/dist-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/usr/local/lib/python2.7/dist-packages/notebook/serverextensions.py", line 210, in start
    self.toggle_server_extension_python(arg)
  File "/usr/local/lib/python2.7/dist-packages/notebook/serverextensions.py", line 199, in toggle_server_extension_python
    m, server_exts = _get_server_extension_metadata(package)
  File "/usr/local/lib/python2.7/dist-packages/notebook/serverextensions.py", line 327, in _get_server_extension_metadata
    m = import_item(module)
  File "/usr/local/lib/python2.7/dist-packages/traitlets/utils/importstring.py", line 42, in import_item
    return __import__(parts[0])
ImportError: No module named jupyter_http_over_ws
```

Tried installing `tornado==5.1` as mentioned in #5 

Also tried upgrading the package:
`pip install --upgrade jupyter_http_over_ws`

**Comment by dronenb** [comment]
How did you install jupyter? Via homebrew? I was having the same issue until I uninstalled all local copies of jupyter installed via pip and pip3, then I followed the instructions [here](https://medium.com/@blessedmarcel1/how-to-install-jupyter-notebook-on-mac-using-homebrew-528c39fd530f) and install the latest version of python via pyenv, then installed jupyter via homebrew. I then did 'pip3 install jupyter_http_over_ws' and the command to enable the extension worked fine.

**Comment by Kshitij09** [comment]
I was working on colab so it was preinstalled

**Comment by fvapolina** [comment]
I uninstalled global (not in venv) jupyter notebook and it worked

**Comment by ethanm88** [comment]
@Kshitij09 I am facing the same issue with Google Colab.

**Comment by Dinkarkumar** [comment]
make sure if your whole working environment is installed with pip then use pip otherwise use pip3.
for example, my whole environment of anaconda , python library, jupyter notebook was installed with pip but i was enabling the second command as you mentioned in question with pip3. I got the same error as you but when i tried installing with pip and enabled using pip , it worked.
![Screenshot from 2020-08-04 00-54-00](https://user-images.githubusercontent.com/42384805/89219261-1127ae00-d5ed-11ea-9fad-b9f7101ca73a.png)
It showed the following error after executing second command.
![Screenshot from 2020-08-04 00-53-46](https://user-images.githubusercontent.com/42384805/89219340-36b4b780-d5ed-11ea-8738-b1b81dad18e4.png)
Then again installed the library using pip as the following.
![Screenshot from 2020-08-04 00-54-14](https://user-images.githubusercontent.com/42384805/89219402-55b34980-d5ed-11ea-9aef-b1c4f369f348.png)
And finally it worked. 
![Screenshot from 2020-08-04 00-53-26](https://user-images.githubusercontent.com/42384805/89219428-6499fc00-d5ed-11ea-9ade-9176f04cc345.png)
Hope it helps.

**Comment by nicoelbert** [comment]
If you installed your enviroment with conda, try to install the jupyter_http_over_ws package also via conda:

    conda install -c conda-forge jupyter_http_over_ws

Then you should be able to enable the serverextension using:
 
    jupyter serverextension enable --py jupyter_http_over_ws
After that run the following code also in PowerShell and you'll receive the url with the tokencode for Colab in there:

    jupyter notebook --NotebookApp.allow_origin='https://colab.research.google.com' \ --port=9090 --no-browser

**Comment by mukteshkrmishra** [comment]
Thanks @nicoelbert , worked for me.

**Comment by ajay-aditatechnologies** [comment]
> make sure if your whole working environment is installed with pip then use pip otherwise use pip3.
> for example, my whole environment of anaconda , python library, jupyter notebook was installed with pip but i was enabling the second command as you mentioned in question with pip3. I got the same error as you but when i tried installing with pip and enabled using pip , it worked.
> ![Screenshot from 2020-08-04 00-54-00](https://user-images.githubusercontent.com/42384805/89219261-1127ae00-d5ed-11ea-9fad-b9f7101ca73a.png)
> It showed the following error after executing second command.
> ![Screenshot from 2020-08-04 00-53-46](https://user-images.githubusercontent.com/42384805/89219340-36b4b780-d5ed-11ea-8738-b1b81dad18e4.png)
> Then again installed the library using pip as the following.
> ![Screenshot from 2020-08-04 00-54-14](https://user-images.githubusercontent.com/42384805/89219402-55b34980-d5ed-11ea-9aef-b1c4f369f348.png)
> And finally it worked.
> ![Screenshot from 2020-08-04 00-53-26](https://user-images.githubusercontent.com/42384805/89219428-6499fc00-d5ed-11ea-9ade-9176f04cc345.png)
> Hope it helps.

Can you please it does work with Ubuntu 20 version

**Comment by deKeijzer** [comment]
> If you installed your enviroment with conda, try to install the jupyter_http_over_ws package also via conda:
> 
> ```
> conda install -c conda-forge jupyter_http_over_ws
> ```
> 
> Then you should be able to enable the serverextension using:
> 
> ```
> jupyter serverextension enable --py jupyter_http_over_ws
> ```
> 
> After that run the following code also in PowerShell and you'll receive the url with the tokencode for Colab in there:
> 
> ```
> jupyter notebook --NotebookApp.allow_origin='https://colab.research.google.com' \ --port=9090 --no-browser
> ```

This is still working, thanks!

**Comment by RobRomijnders** [comment]
+1 to reply by @dronenb . Installing jupyter notebook in a new virtualenv worked for me (i.e. such that the system jupyter is not used).

**Comment by gift-exe** [comment]
I've tried installing jupyter_http_over_ws_extension with pip, pip3, and conda. It installs successfully but when I try to enable it I get this error.

![Screenshot from 2023-01-16 10-48-29](https://user-images.githubusercontent.com/82771483/212648739-e1292179-757c-4d2c-9dc0-ce53b2a277ed.png)

"jupyter serverextension enable --py jupyter_http_over_ws", is what I'm trying to use to enable the library

I read the markupsafe/__init__.py file and did not see a function or method named "soft_unicode".

I'd appreciate it if you tell me what to do to fix this error.

**Comment by RobRomijnders** [comment]
For me, the issue was fixed after re-install. Did you try that?

Also, your prompt starts with `(base) $`. Are you sure you did the installs in the (base) environment? I would recommend to make a separate environment to avoid confusion of versions.
