### ISSUE TITLE
 Error loading server extension —

### ISSUE THREAD

**Issue by Geobm** [googlecolab/jupyter_http_over_ws#21]
I'm trying to connect to a local runtime, but I'm getting the following error: `Error loading server extension —`.
```
jupyter_http_over_ws extension initialized. Listening on /http_over_websocket
[I 00:55:51.130 NotebookApp] JupyterLab extension loaded from C:\Users\Issstezac1\anaconda3\lib\site-pack
ages\jupyterlab
[I 00:55:51.130 NotebookApp] JupyterLab application directory is C:\Users\Issstezac1\anaconda3\share\jupy
ter\lab
[W 00:55:51.146 NotebookApp] Error loading server extension —
    Traceback (most recent call last):
      File "C:\Users\Issstezac1\anaconda3\lib\site-packages\notebook\notebookapp.py", line 1670, in init_
server_extensions
        mod = importlib.import_module(modulename)
      File "C:\Users\Issstezac1\anaconda3\lib\importlib\__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
      File "<frozen importlib._bootstrap>", line 983, in _find_and_load
      File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
    ModuleNotFoundError: No module named '—'
[I 00:55:51.146 NotebookApp] Serving notebooks from local directory: C:\
[I 00:55:51.146 NotebookApp] The Jupyter Notebook is running at:
[I 00:55:51.146 NotebookApp] http://localhost:8888/?token=8a32f41c430162d354daec4e588d7de6caa6b84924436b5
7
[I 00:55:51.146 NotebookApp]  or http://127.0.0.1:8888/?token=8a32f41c430162d354daec4e588d7de6caa6b849244
36b57
[I 00:55:51.146 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip c
onfirmation).
[C 00:55:51.224 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/Issstezac1/AppData/Roaming/jupyter/runtime/nbserver-6840-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=8a32f41c430162d354daec4e588d7de6caa6b84924436b57
     or http://127.0.0.1:8888/?token=8a32f41c430162d354daec4e588d7de6caa6b84924436b57
```
 I followed every [step]( https://research.google.com/colaboratory/local-runtimes.html) from the documentation but I still can not connect locally. Currently, I'm using Mozilla 77.0.1 (64-bit) version. Therefore, I enabled ` network.websocket.allowInsecureFromHTTPS` as mentioned in the specific browser settings. Even I tried the `  --no-browser` flag as the [Jupyter HTTP-over-WebSocket](https://github.com/googlecolab/jupyter_http_over_ws/blob/master/README.md#troubleshooting) troubleshooting suggest. What am I doing wrong?

 Any further help will be appreciated.

**Comment by tchen-otterai** [comment]
I have the same issue though I am using chrome.
