### ISSUE TITLE
Jupyter notebook won't connect to kernel

### ISSUE THREAD

**Issue by fuzzyman27** [googlecolab/jupyter_http_over_ws#7]
I installed this extension and now my jupyter won't run anything as it can't connect to the terminal. Please advise on how I can troubleshoot/uninstall this extension. Thanks!

**Comment by colaboratory-team** [comment]
Sorry to hear that you're having trouble here. When you encounter the kernel connection issue described above, are there any error messages printed in the console where you invoked the "jupyter notebook" command?

The extension can be uninstalled by running:
```
jupyter serverextension disable --py jupyter_http_over_ws
pip uninstall jupyter_http_over_ws
```

**Comment by sorginetxe** [comment]
Jupyter can't connect to kerne after pip3 install google-colab. I'm getting the following error :  

`404 GET /nbextensions/widgets/notebook/js/extension.js?v=20200110011218 (127.0.0.1) 1.33ms referer=http://localhost:8889/notebooks/pyProjects/sitemapExplorer/sitemapExplorer.ipynb
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ts/.local/lib/python3.6/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/home/ts/.local/lib/python3.6/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/home/ts/.local/lib/python3.6/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/home/ts/.local/lib/python3.6/site-packages/IPython/__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "/home/ts/.local/lib/python3.6/site-packages/IPython/terminal/embed.py", line 18, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/home/ts/.local/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 16, in <module>
    from prompt_toolkit.document import Document
  File "/home/ts/.local/lib/python3.6/site-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "/home/ts/.local/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "/home/ts/.local/lib/python3.6/site-packages/prompt_toolkit/application/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/ts/.local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 36, in <module>
    from prompt_toolkit.buffer import Buffer
  File "/home/ts/.local/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 9, in <module>
    from .completion import Completer, Completion, CompleteEvent
  File "/home/ts/.local/lib/python3.6/site-packages/prompt_toolkit/completion/__init__.py", line 1, in <module>
    from .base import (
  File "/home/ts/.local/lib/python3.6/site-packages/prompt_toolkit/completion/base.py", line 7, in <module>
    from prompt_toolkit.eventloop import generator_to_async_generator
ImportError: cannot import name 'generator_to_async_generator'
`
After 5 Kernel restart attempt I get  a segmentation error (core dumped) in the terminal and jupyter stops running. 

When I restart jupyter notebook, kernel can't connect. I get the following error in my my shell

`WARNING:root:kernel e3c3b33c-a857-4649-83f2-ffc9a073f03c restarted
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ts/.local/lib/python3.6/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/home/ts/.local/lib/python3.6/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/home/ts/.local/lib/python3.6/site-packages/ipykernel/connect.py", line 13, in <module>
    from IPython.core.profiledir import ProfileDir
  File "/home/ts/.local/lib/python3.6/site-packages/IPython/__init__.py", line 49, in <module>
    from .terminal.embed import embed
  File "/home/ts/.local/lib/python3.6/site-packages/IPython/terminal/embed.py", line 18, in <module>
    from IPython.terminal.interactiveshell import TerminalInteractiveShell
  File "/home/ts/.local/lib/python3.6/site-packages/IPython/terminal/interactiveshell.py", line 16, in <module>
    from prompt_toolkit.document import Document
  File "/home/ts/.local/lib/python3.6/site-packages/prompt_toolkit/__init__.py", line 16, in <module>
    from .interface import CommandLineInterface
  File "/home/ts/.local/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 19, in <module>
    from .application import Application, AbortAction
  File "/home/ts/.local/lib/python3.6/site-packages/prompt_toolkit/application/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/ts/.local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 36, in <module>
    from prompt_toolkit.buffer import Buffer
  File "/home/ts/.local/lib/python3.6/site-packages/prompt_toolkit/buffer.py", line 9, in <module>
    from .completion import Completer, Completion, CompleteEvent
  File "/home/ts/.local/lib/python3.6/site-packages/prompt_toolkit/completion/__init__.py", line 1, in <module>
    from .base import (
  File "/home/ts/.local/lib/python3.6/site-packages/prompt_toolkit/completion/base.py", line 7, in <module>
    from prompt_toolkit.eventloop import generator_to_async_generator
ImportError: cannot import name 'generator_to_async_generator'
`
Note that jupyter_http_over_ws is not installed
